config/routes.rb
Rails.application.routes.draw do

  # get 'bill_checks/index'
  #
  # get 'bill_checks/new'
  #
  # get 'bill_checks/create'
  #
  # get 'bill_checks/show'
  #
  # get 'bill_checks/update'
  #
  # get 'bill_checks/edit'
  #
  # get 'bill_check/index'
  #
  # get 'bill_check/new'
  #
  # get 'bill_check/show'
  #
  # get 'bill_check/edit'
  #
  # get 'bill_check/update'
  #
  # get 'bill_check/create'

  # get 'users/index'
  #
  # get 'users/viewmenu'
  #
  # get 'users/order_history'
  #
  # get 'users/logout_user'

  # get 'table_management2s/create'

  # get 'table_managements2/index'
  #
  # get 'table_managements2/create'
  #
  # get 'table_managements2/show'
  #
  # get 'table_managements2/new'

  # get 'table_managements/create'
  #
  # get 'table_managements/new'
  #
  # get 'table_managements/index'
  #
  # get 'table_managements/show'
  #
  # get 'table_managements/edit'
  #
  # get 'table_managements/delete'
  #
  # get 'menu_managements/index'
  #
  # get 'menu_managements/new'
  #
  # get 'menu_managements/show'
  #
  # get 'menu_managements/create'
  #
  # get 'menu_managements/edit'
  #
  # get 'menu_managements/delete'
  #
  # get 'select_branches/index'
  #
  # get 'select_branches/new'
  #
  # get 'select_branches/create'
  #
  # get 'select_branches/show'
  #
  # get 'makebrs/index'
  #
  # get 'makebrs/new'
  #
  # get 'makebrs/show'
  #
  # get 'makebs/index'
  #
  # get 'makebs/new'
  #
  # get 'makebranches/index'
  #
  # get 'makebranches/new'
  #
  # get 'makebranch/index'
  #
  # get 'makebranch/create'
  #
  # get 'makebranch/show'
  #
  # get 'makebranch/new'
  #
  # get 'make_branches/index'
  #
  # get 'make_branches/new'
  #
  # get 'make_branches/show'
  #
  # get 'make_branches/create'
  #
  # get 'make_branch/index'
  #
  # get 'make_branch/create'
  #
  # get 'make_branch/show'
  #
  # get 'make_branch/new'
  #
  # get 'session2/create'
  root 'homes#index'

  get 'users/order_history'
  get 'users/menual_user'


  resources :homes
  resources :sessions
  resources :select_branches
  resources :operators
  resources :makebrs
  resources :users
  resources :menu_managements
  get 'menu_managements/new/:br_id' => 'menu_managements#new'
  # get 'menu_managements/index/:br_id' => 'menu_managements#index'
  resources :table_management2s
  resources :table_managements
  resources :bill_checks
  get 'table_managements/new/:br_id' => 'table_managements#new'
  get 'table_managements/index/:br_id' => 'table_managements#index'
  get 'menu_managements/create/:br_id' => 'menu_managements#create'
  delete 'menu_managements/destroy/:br_id' => 'menu_managements#destroy'
  get 'menu_managements/delete/:br_id' => 'menu_managements#delete'
  get 'menu_managements/update/:br_id' => 'menu_managements#update'
  get 'menu_managements/edit/:br_id' => 'menu_managements#edit'
  get 'bill_check/show/:br_id' => 'bill_check#show'
  get 'bill_check/index/:br_id' => 'bill_check#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord

  has_many :seat_strutures
  belongs_to :operator

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :orders
  belongs_to :branch
  mount_uploader :image, AvatarUploader
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :branches
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  before_save {self.email=email.downcase}
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true,
            format:{with: VALID_EMAIL_REGEX},
           uniqueness: {case_sensitive: false}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :menu
  belongs_to :seat_onuse
end

app/models/seat_onuse.rb
class SeatOnuse < ApplicationRecord
  has_many :orders
  belongs_to :seat_struture, optional: true
end

app/models/seat_struture.rb
class SeatStruture < ApplicationRecord
  belongs_to :branch
  has_many :seat_onuses
end

app/models/user.rb
class User < ApplicationRecord

  has_many :branches

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new

  end

  #회원가입 하면 여기로 데이터 옴
  def create

  end

  def show

  end

  def index

  end

end

app/controllers/makebrs_controller.rb
class MakebrsController < ApplicationController
  def index
    @op = Operator.where(operator_id: session[:operator_id])
  end

  def new
    @token = form_authenticity_token
  end

  def show
  end

  def create
    op_id = params[:op_id].to_s
    @br = Branch.create(
        universe: params[:branch_school],
        major: params[:branch_major],
        operator_id: op_id
    )

    redirect_to select_branches_path  # 브렌치 선택으로 이동.
  end
end

app/controllers/menu_managements_controller.rb
class MenuManagementsController < ApplicationController
  def index

  end

  def create
    @token = form_authenticity_token
    @menu = Menu.create(
        name: params[:menu][:name],
        price: params[:menu][:price],
        branch_id: params[:br_id]
    )
    redirect_to '/menu_managements/new/' + '/' + params[:br_id]
  end

  def show

  end

  def index

  end

  def edit
    @token = form_authenticity_token
    @menu123 = Menu.find(params[:m_id])
    @menu123.id = params[:m_id]
    @menu123.name = params[:m_name]
    @menu123.content = params[:m_content]
  end

  def destroy
    menu = Menu.find(params[:id])
    Menu.destroy(params[:id])

    redirect_to '/menu_managements/new/' + '/' + params[:br_id]
  end

  def new
    @menu_id = Menu.where(branch_id: params[:br_id])
  end

  def update
    @toekn = form_authenticity_token

    menu = Menu.find(params[:id])
    menu.name = params[:menu][:name]
    menu.price = params[:menu][:price]
    menu.content = params[:menu][:content]

    redirect_to '/menu_managements/new/' + '/' + params[:br_id]

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, :only => :create
  def create
      #로그인 확인
      confirm_id=params[:op_id]

      if confirm_id.include?"@"
        #운영자 아이디면
        operator=Operator.find_by(email: params[:op_id])
        if operator && operator.authenticate(params[:password])
          log_in_operator(operator)
          redirect_to select_branches_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end

      else
        #사용자 아이디면
        table=SeatOnuse.find(params[:op_id])
        if table && table.hash_code==params[:password]
          log_in_user(table)
          redirect_to users_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end
      end

  end

  def destroy
    log_out
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def viewmenu
  end

  def index
  end

  def order_history
  end

  def logout_user
  end

  def menual_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_checks_helper.rb
module BillChecksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/makebrs_helper.rb
module MakebrsHelper
end

app/helpers/menu_managements_helper.rb
module MenuManagementsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/select_branches_helper.rb
module SelectBranchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in_operator(operator)
    session[:operator_id]=operator.id
  end

  def log_in_user(table)
    session[:table_id]=table.id
  end

  def confirm_log_in?(confirm_id)
    #마지막줄 리턴
    email_format==/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  end

  def current_operator
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

   @current_operator ||= Operator.find_by(id: session[:operator_id])
  end

  def current_user
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

    @current_user||= SeatOnuse.find(session[:table_id])
  end

  def operator_signed_in?
    !current_operator.nil?
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/menu_managements/create.html.erb
<h1>power</h1>

app/views/menu_managements/edit.html.erb
<%= link_to '메뉴________', '#'%>
<%= link_to '테이블________', '/table_managements/new/' + params[:br_id] %>
<%= link_to '주문 현황 보기________', '#' %>
<a href="https://www.youtube.com/watch?v=Jitf9tgAJEw&index=7&list=RD5shZgGNGs58">사용법</a>
<br><br><br>
+--------------------+<br>
| 메뉴를 수정해 주세요 |<br>
+--------------------+<br>
<%= form_for(@menu123, url: menu_management_path, method: "put") do |f| %>
  <%= f.label :name, '이름' %>
  <%= f.text_field :name, required: true %> <br>

  <%= f.label :price, '가격' %>
  <%= f.number_field :price, required: true %> <br>

  <%= f.label :content, '내용' %>
  <%= f.text_area :content, required: true %> <br>

  <%= hidden_field_tag 'br_id', params[:br_id] %>
  <%= f.submit '수정하기' %>
<% end %>

app/views/menu_managements/index.html.erb
<h1>메뉴 게시판</h1>

<br><br>
<%= link_to '메뉴만들기', '/menu_managements/new/'+params[:br_id] %>
<br><br>
<%= link_to '메뉴 수정하기', '#' %>
<br><br>
<%= link_to '메뉴 삭제하기', '#' %>

app/views/menu_managements/new.html.erb
      <%= form_for(Menu.new, url: menu_managements_path, method: "post") do |f| %>
        <div class="operator_wrap">
          <% if operator_signed_in? %>
            로그인한 유저:
            <%= current_operator.email %>
          <% end %>
          <p><%= link_to '로그아웃', session_path(current_operator.email), method: 'delete' %></p>
          <div class="operator_logo"></div>
          <nav class="operator_bar_nav">
            <ul class="operator_bar_list">
              <hr>
              <%= link_to '주문 현황', '/bill_checks/index/' + params[:br_id] %>
              <%= link_to '테이블 만들기', '/table_managements/new/' + params[:br_id] %>
              <a class="menu_icon" href="#">메뉴</a>
              <a href="https://www.youtube.com/watch?v=Jitf9tgAJEw&index=7&list=RD5shZgGNGs58">사용법</a>
              <hr>
            </ul>
            <ul class="menu_bar">
              <div class="test">
                <%= link_to '메뉴 생성', '/menu_managements/new/' + params[:br_id] %>
                <a href="#">메뉴 수정</a>
                <a href="#">메뉴 삭제</a>
              </div>
            </ul>

          </nav>


          <section class="create_menu_section"><!-- 상단바 밑 전체 화면 -->
            <h1>메뉴 생성</h1>

            <div class="add_box">

              <div class="add_menu_click">
                <%= image_tag "Add-icon.png", class: "plus_icon" %>
              </div><!-- add_menu_click end -->

              <div class="add_menu_detail">
                <table class="menu-table">
                  <tr>
                    <td>
                      <input type="file"><br>
                    </td>
                  <tr>
                    <td>
                      <%= f.label :title, '메뉴명' %>
                      <%= f.text_field :name, required: true %> <br>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <%= f.label :contents, '가격' %>&nbsp&nbsp&nbsp
                      <%= f.number_field :price, required: true %> <br>
                      <%= hidden_field_tag 'br_id', params[:br_id] %>
                      <%= f.submit '생성' %>
                    </td>
                  </tr>

                </table>
              </div><!-- add_menu_detail end -->
            </div>
            <% @menu_id.each do |x| %>
              <div>

                <%= x.name %> <%= x.price %> 원</p>
                <p><%= x.content %></p>

                <form action="<%= edit_menu_management_path (x.id) %>">
                  <input type="hidden" name="authenticity_token" value="<%= @token %>">
                  <input type="hidden" name="m_id" value="<%= x.id %>">
                  <input type="hidden" name="br_id" value="<%= x.branch_id %>">
                  <input type="hidden" name="m_name" value="<%= x.name %>">
                  <input type="hidden" name="m_price" value="<%= x.price %>">
                  <input type="hidden" name="m_content" value="<%= x.content %>">
                  <input type="submit" value="수정하기">
                </form>

                <%= link_to menu_management_path(x.id), method: 'delete' do %>
                  <input type="hidden" name="authenticity_token" value="<%= @token %>">
                  <button>삭제하기</button>
                  <br>
                <% end %>
              </div>
            <% end %>



          </section><!-- create section end -->
        </div>
      <% end %>

app/views/menu_managements/show.html.erb
<h1>메뉴.</h1>
<% @menu_struct.each do |x| %>  <!-- 반복문! -->
  제목 : <%= x.name %> <br>
  내용 : <%= x.price %> <br>
  <a href= <%  menu_managements_path method: "delete"%> <%= x.id%>">삭제</a>
  <hr>
<%end%>

<h1>메뉴 만들기</h1>


<form action="<%= menu_managements_path %>" method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
이름 : <input type="text" name="menu_name" placeholder="이름"> <br>
가격 : <input type="text" name="menu_price" placeholder="가격"> <br>
<input type="submit" value="만들기">
</form>

<a href="/"> 홈으로 가기</a>