config/routes.rb
Rails.application.routes.draw do

  # get 'bill_checks/index'
  #
  # get 'bill_checks/new'
  #
  # get 'bill_checks/create'
  #
  # get 'bill_checks/show'
  #
  # get 'bill_checks/update'
  #
  # get 'bill_checks/edit'
  #
  # get 'bill_check/index'
  #
  # get 'bill_check/new'
  #
  # get 'bill_check/show'
  #
  # get 'bill_check/edit'
  #
  # get 'bill_check/update'
  #
  # get 'bill_check/create'

  # get 'users/index'
  #
  # get 'users/viewmenu'
  #
  # get 'users/order_history'
  #
  # get 'users/logout_user'

  # get 'table_management2s/create'

  # get 'table_managements2/index'
  #
  # get 'table_managements2/create'
  #
  # get 'table_managements2/show'
  #
  # get 'table_managements2/new'

  # get 'table_managements/create'
  #
  # get 'table_managements/new'
  #
  # get 'table_managements/index'
  #
  # get 'table_managements/show'
  #
  # get 'table_managements/edit'
  #
  # get 'table_managements/delete'
  #
  # get 'menu_managements/index'
  #
  # get 'menu_managements/new'
  #
  # get 'menu_managements/show'
  #
  # get 'menu_managements/create'
  #
  # get 'menu_managements/edit'
  #
  # get 'menu_managements/delete'
  #
  # get 'select_branches/index'
  #
  # get 'select_branches/new'
  #
  # get 'select_branches/create'
  #
  # get 'select_branches/show'
  #
  # get 'makebrs/index'
  #
  # get 'makebrs/new'
  #
  # get 'makebrs/show'
  #
  # get 'makebs/index'
  #
  # get 'makebs/new'
  #
  # get 'makebranches/index'
  #
  # get 'makebranches/new'
  #
  # get 'makebranch/index'
  #
  # get 'makebranch/create'
  #
  # get 'makebranch/show'
  #
  # get 'makebranch/new'
  #
  # get 'make_branches/index'
  #
  # get 'make_branches/new'
  #
  # get 'make_branches/show'
  #
  # get 'make_branches/create'
  #
  # get 'make_branch/index'
  #
  # get 'make_branch/create'
  #
  # get 'make_branch/show'
  #
  # get 'make_branch/new'
  #
  # get 'session2/create'
  root 'homes#index'

  get 'users/order_history'
  get 'users/menual_user'


  resources :homes
  resources :sessions
  resources :select_branches
  resources :operators
  resources :makebrs
  resources :users
  resources :menu_managements
  get 'menu_managements/new/:br_id' => 'menu_managements#new'
  # get 'menu_managements/index/:br_id' => 'menu_managements#index'
  resources :table_management2s
  resources :table_managements
  resources :bill_checks
  get 'table_managements/new/:br_id' => 'table_managements#new'
  get 'table_managements/index/:br_id' => 'table_managements#index'
  get 'menu_managements/create/:br_id' => 'menu_managements#create'
  delete 'menu_managements/destroy/:br_id' => 'menu_managements#destroy'
  get 'menu_managements/delete/:br_id' => 'menu_managements#delete'
  get 'menu_managements/update/:br_id' => 'menu_managements#update'
  get 'menu_managements/edit/:br_id' => 'menu_managements#edit'
  get 'bill_check/show/:br_id' => 'bill_check#show'
  get 'bill_check/index/:br_id' => 'bill_check#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord

  has_many :seat_strutures
  belongs_to :operator

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :orders
  belongs_to :branch
  mount_uploader :image, AvatarUploader
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :branches
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  before_save {self.email=email.downcase}
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true,
            format:{with: VALID_EMAIL_REGEX},
           uniqueness: {case_sensitive: false}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :menu
  belongs_to :seat_onuse
end

app/models/seat_onuse.rb
class SeatOnuse < ApplicationRecord
  has_many :orders
  belongs_to :seat_struture, optional: true
end

app/models/seat_struture.rb
class SeatStruture < ApplicationRecord
  belongs_to :branch
  has_many :seat_onuses
end

app/models/user.rb
class User < ApplicationRecord

  has_many :branches

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new

  end

  #회원가입 하면 여기로 데이터 옴
  def create

  end

  def show

  end

  def index

  end

end

app/controllers/makebrs_controller.rb
class MakebrsController < ApplicationController
  def index
    @op = Operator.where(operator_id: session[:operator_id])
  end

  def new
    @token = form_authenticity_token
  end

  def show
  end

  def create
    op_id = params[:op_id].to_s
    @br = Branch.create(
        universe: params[:branch_school],
        major: params[:branch_major],
        operator_id: op_id
    )

    redirect_to select_branches_path  # 브렌치 선택으로 이동.
  end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  def create
    @op=Operator.create(
                  email: params[:email],
                  password: params[:password],
                  phone: params[:operator_phone],
                  name: params[:operator_name]
    )

    redirect_to '/homes#index'
  end

  def index

  end
  def show

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, :only => :create
  def create
      #로그인 확인
      confirm_id=params[:op_id]

      if confirm_id.include?"@"
        #운영자 아이디면
        operator=Operator.find_by(email: params[:op_id])
        if operator && operator.authenticate(params[:password])
          log_in_operator(operator)
          redirect_to select_branches_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end

      else
        #사용자 아이디면
        table=SeatOnuse.find(params[:op_id])
        if table && table.hash_code==params[:password]
          log_in_user(table)
          redirect_to users_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end
      end

  end

  def destroy
    log_out
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def viewmenu
  end

  def index
  end

  def order_history
  end

  def logout_user
  end

  def menual_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_checks_helper.rb
module BillChecksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/makebrs_helper.rb
module MakebrsHelper
end

app/helpers/menu_managements_helper.rb
module MenuManagementsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/select_branches_helper.rb
module SelectBranchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in_operator(operator)
    session[:operator_id]=operator.id
  end

  def log_in_user(table)
    session[:table_id]=table.id
  end

  def confirm_log_in?(confirm_id)
    #마지막줄 리턴
    email_format==/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  end

  def current_operator
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

   @current_operator ||= Operator.find_by(id: session[:operator_id])
  end

  def current_user
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

    @current_user||= SeatOnuse.find(session[:table_id])
  end

  def operator_signed_in?
    !current_operator.nil?
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
  end
end

app/helpers/table_managements_helper.rb
module TableManagementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/operators/create_menu.html.erb
<div class="operator_wrap">
  <p><a href="#">로그아웃</a></p>
  <div class="operator_logo"></div>
  <nav class="operator_bar_nav">
    <ul class="operator_bar_list">
      <hr>
      <a href="#">테이블 현황</a>
      <a href="#">테이블 생성</a>
      <a class="menu_icon" href="#">메뉴</a>
      <a href="#">사용법</a>
      <hr>
    </ul>
    <ul class="menu_bar">
      <div class="test">
        <a href="#">메뉴 생성</a>
        <a href="#">메뉴 수정</a>
        <a href="#">메뉴 삭제</a>
      </div>
    </ul>

  </nav>

  <section class="create_menu_section"><!-- 상단바 밑 전체 화면 -->
    <h1>메뉴 생성</h1>

    <div class="add_box">

      <div class="add_menu_click">
        <%= image_tag "Add-icon.png", class: "plus_icon" %>
        메뉴 추가
      </div><!-- add_menu_click end -->

      <div class="add_menu_detail">
        <table>
          <tr>
            <input type="file">
          <tr>
            <td>메뉴명 :</td>
            <td><input type="text"></td>
          </tr>
          <tr>
            <td>가격 :</td>
            <td>
              <input type="number">
              <input type="submit" value="생성">
            </td>
          </tr>

        </table>
      </div><!-- add_menu_detail end -->
    </div>

  </section><!-- create section end -->
</div>

app/views/operators/delete_menu.html.erb
<div class="operator_wrap">
  <p><a href="#">로그아웃</a></p>
  <div class="operator_logo"></div>
  <nav class="operator_bar_nav">
    <ul class="operator_bar_list">
      <hr>
      <a href="#">테이블 현황</a>
      <a href="#">테이블 생성</a>
      <a class="menu_icon" href="#">메뉴</a>
      <a href="#">사용법</a>
      <hr>
    </ul>
    <ul class="menu_bar">
      <div class="test">
        <a href="#">메뉴 생성</a>
        <a href="#">메뉴 수정</a>
        <a href="#">메뉴 삭제</a>
      </div>
    </ul>

  </nav>
  <section class="delete_menu_section"><!-- 상단바 밑 전체 화면 -->
    <h1>메뉴 삭제</h1>


    <div class="delete_box">

      <div class="delete_menu_click">
        <%= image_tag "Recyclebin.png", class: "delete_icon" %>
        메뉴 삭제
      </div><!-- delete_menu_click end -->
    </div>

  </section>
</div>

app/views/operators/edit_menu.html.erb
<div class="operator_wrap">
  <p><a href="#">로그아웃</a></p>
  <div class="operator_logo"></div>
  <nav class="operator_bar_nav">
    <ul class="operator_bar_list">
      <hr>
      <a href="#">테이블 현황</a>
      <a href="#">테이블 생성</a>
      <a class="menu_icon" href="#">메뉴</a>
      <a href="#">사용법</a>
      <hr>
    </ul>
    <ul class="menu_bar">
      <div class="test">
        <a href="#">메뉴 생성</a>
        <a href="#">메뉴 수정</a>
        <a href="#">메뉴 삭제</a>
      </div>
    </ul>

  </nav>
  <section class="edit_menu_section"><!-- 상단바 밑 전체 화면 -->
    <h1>메뉴 수정</h1>
  </section>
</div>

app/views/operators/index.html.erb
<!--<h1>지점 </h1>-->
<!--<br><br><br>-->
<!--<%#= link_to '회원가입', new_home_path %><br>-->
<%#= link_to '메뉴', 'menu_managements/index/'+params[:br_id]%>
<!--<br><br>-->

<%#= link_to '테이블', 'table_managements/index/'+params[:br_id]%>


<!--<br><br>-->
<%#= link_to '주문 현황 보기', '#' %>
<!--<br><br>-->
<!--<a href="https://www.youtube.com/watch?v=Jitf9tgAJEw&index=7&list=RD5shZgGNGs58">사용법</a>-->
<!--<br><br>-->

<!--홍준이형-->

<div class="operator_wrap">
<% if operator_signed_in? %>
    로그인한 유저:
<%= current_operator.email %>
<% end %>
  <p><%= link_to '로그아웃', session_path(current_operator.email), method: 'delete' %></p>
  <div class="operator_logo"></div>
  <nav class="operator_bar_nav">
    <ul class="operator_bar_list">
      <hr>
      <a href="#">테이블 현황</a>
      <a href="#">테이블 생성</a>
      <%= link_to '메뉴', '/menu_managements/new/'+params[:br_id] %>
      <a href="#">사용법</a>
      <hr>
    </ul>
    <ul class="menu_bar">
      <div class="test">
        <%= link_to '메뉴 생성', '/menu_managements/new/'+params[:br_id] %>
        <a href="#">메뉴 수정</a>
        <a href="#">메뉴 삭제</a>
      </div>
    </ul>

  </nav>

</div>
<div class="table-status">
  <section class="table-status-left">
    <ul>
      <li><a href="#">테이블 배치</a></li>
      <li><a href="#">주문 내역</a></li>
      <li><a href="#">매 출</a></li>
    </ul>
  </section>

  <section class="table-status-middle">

    <article class="table-num1"><a href="#"><img src="" alt=""></a></article>
    <article class="table-num2"><a href="#"><img src="" alt=""></a></article>
    <article class="table-num3"><a href="#"><img src="" alt=""></a></article>
    <article class="table-num4"><a href="#"><img src="" alt=""></a></article>
    <article class="table-num5"><a href="#"><img src="" alt=""></a></article>
    <article class="table-num6"><a href="#"><img src="" alt=""></a></article>
    <article class="table-num7"><a href="#"><img src="" alt=""></a></article>
    <article class="table-num8"><a href="#"><img src="" alt=""></a></article>

  </section>

</div>
</section>

app/views/operators/new.html.erb
<form action="<%= operators_path %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="register_wrap">
    <header class="register_logo"></header>
    <section class="register_display">

      <table>
        <tr>

          <td>아이디 </td>
          <td><input type="email" name="email" placeholder="이메일"></td>
        </tr>
        <tr>
          <td>비밀번호 </td>
          <td><input type="password" id="Pw" name="password" required></td>
        </tr>
        <tr>
          <td>비밀번호 확인 </td>
          <td>
            <input type="password" id="PwCheck" name="password_confirmation" required>
<!--            <p id="pwsame" class="pwsame" style="color:red;"></p>-->
            <br><br>
          </td>
        </tr>

        <tr>
          <td>이름</td>
          <td><input type="text" name="operator_name"></td>
        </tr>
        <tr>
          <td>전화번호</td>
          <td><input type="number" name="operator_phone"></td>
        </tr>
      </table>

      <input class="next_register" type="submit" value="확인">
    </section> <!-- login_display end -->
  </div> <!-- login_wrap end -->
</form>

app/views/operators/show.html.erb
<% @br.each do |x| %>
  <div>
    <p><%=x.id%></p>

    <form action="<%= operators_path%>" method="get">
      <input type="hidden" name = "authenticity_token" value="<%=@token%>">
      <input type="hidden" name = "op_id" value = "<%=x.id%>">
      <input type="submit" value="지점 이동">
    </form>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="user_wrap">
  <% if user_signed_in? %>
    로그인한 테이블:
    <%= current_user.id %>
  <% end %>
  <p><%= link_to '로그아웃', session_path(current_user.id), method: 'delete' %></p>  <!-- 로그아웃되게 해주세요.... -->
  <a href="/users#index">
    <div class="user_logo"></div>
  </a>
  <nav class="user_bar_nav">
    <ul class="user_bar_list">
      <hr>
      <%= link_to '주문하기', users_path %>
      <%= link_to '주문내역', '/users/order_history' %>
      <%= link_to '사용법', '/users/menual_user' %>
      <hr>
    </ul>
  </nav>
</div>
<section class="order">
  <article class="order-num1">
    <div class="order-num1-image"></div>ㅡ
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num2">
    <div class="order-num2-image"></div>
    <p>1</p>
    <p>2</p>
  </article>


  <article class="order-num3">
    <div class="order-num3-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num4">
    <div class="order-num4-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num5">
    <div class="order-num5-image"></div>
    <p>1</p>
    <p>2</p>
  </article>


  <article class="order-num6">
    <div class="order-num6-image"></div>
    <p>1</p>
    <p>2</p>
  </article>


  <article class="order-num7">
    <div class="order-num7-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num8">
    <div class="order-num8-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <input class="submit" type="submit" value="주문하기">


</section>

app/views/users/logout_user.html.erb
<h1>User#logout_user</h1>
<p>Find me in app/views/user/logout_user.html.erb</p>

app/views/users/menual_user.html.erb
<div class="user_wrap">
  <% if operator_signed_in? %>
    로그인한 유저:
    <%= current_operator.user_id %>
  <% end %>
  <p><%= link_to '로그아웃', session_path(current_operator.user_id), method: 'delete' %></p>  <!-- 로그아웃되게 해주세요.... -->
  <a href="/users#index">
    <div class="user_logo"></div>
  </a>
  <nav class="user_bar_nav">
    <ul class="user_bar_list">
      <hr>
      <%= link_to '주문하기', users_path %>
      <%= link_to '주문내역', '/users/order_history' %>
      <%= link_to '사용법', '/users/menual_user' %>
      <hr>
    </ul>
  </nav>
</div>

<section class="video">

  <iframe width="668" height="376" src="https://www.youtube.com/embed/3MRvKJZEd6w" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

</section>

app/views/users/order.html.erb
<div class="user_wrap">
  <p><a href="#">로그아웃</a></p>  <!-- 로그아웃되게 해주세요.... -->
  <div class="user_logo"></div>
  <nav class="user_bar_nav">
    <ul class="user_bar_list">
      <hr>
      <a href="#">주문하기</a>
      <a href="#">주문내역</a>
      <a href="#">사용법</a>
      <hr>
    </ul>
  </nav>
</div>




<section class="order">
  <article class="order-num1">
    <div class="order-num1-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num2">
    <div class="order-num2-image"></div>
    <p>1</p>
    <p>2</p>
  </article>


  <article class="order-num3">
    <div class="order-num3-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num4">
    <div class="order-num4-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num5">
    <div class="order-num5-image"></div>
    <p>1</p>
    <p>2</p>
  </article>


  <article class="order-num6">
    <div class="order-num6-image"></div>
    <p>1</p>
    <p>2</p>
  </article>


  <article class="order-num7">
    <div class="order-num7-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <article class="order-num8">
    <div class="order-num8-image"></div>
    <p>1</p>
    <p>2</p>
  </article>

  <input class="submit" type="submit" value="주문하기">


</section>

app/views/users/order_history.html.erb
<div class="user_wrap">
  <% if operator_signed_in? %>
    로그인한 유저:
    <%= current_operator.user_id %>
  <% end %>
  <p><%= link_to '로그아웃', session_path(current_operator.user_id), method: 'delete' %></p>  <!-- 로그아웃되게 해주세요.... -->
  <a href="/users#index">
    <div class="user_logo"></div>
  </a>
  <nav class="user_bar_nav">
    <ul class="user_bar_list">
      <hr>
      <%= link_to '주문하기', users_path %>
      <%= link_to '주문내역', '/users/order_history' %>
      <%= link_to '사용법', '/users/menual_user' %>
      <hr>
    </ul>
  </nav>
</div>

<div class="order-history">
  <section class="order-history-table">
    <li>No.3</li>  <!-- 테이블 정보를 받아서 그수 를 출력-->
  </section> <!-- index-history-table-->

  <section class="order-history-menu">
    <ul>
      <li class="order-history-menu-top">주문한 메뉴</li>
    </ul>
    <section class="order-history-menu-bottum">
      <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
      </ul>
    </section><!--index-history-menu-bottum-->

    <section class="order-history-menu-bottum-total">
    <ul>
      <li>총        합</li>
    </ul>
    </section><!--index-history-menu-bottum-total-->

  </section><!--index-history-menu-->

  <section class="order-history-price"><ul>
    <li class="order-history-menu-price">가격</li>
  </ul>
    <section class="order-history-price-bottum">
      <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
      </ul>

    </section><!--index-history-price-bottum-->
    <section class="order-history-price-bottum-total">
      <ul>
        <li>30000</li>
      </ul>
    </section><!--index-history-menu-bottum-total-->


  </section><!--index-history-price-->

</div> <!-- index-history-->

app/views/users/viewmenu.html.erb
<h1>User#viewmenu</h1>
<p>Find me in app/views/user/viewmenu.html.erb</p>