config/routes.rb
Rails.application.routes.draw do

  # get 'bill_checks/index'
  #
  # get 'bill_checks/new'
  #
  # get 'bill_checks/create'
  #
  # get 'bill_checks/show'
  #
  # get 'bill_checks/update'
  #
  # get 'bill_checks/edit'
  #
  # get 'bill_check/index'
  #
  # get 'bill_check/new'
  #
  # get 'bill_check/show'
  #
  # get 'bill_check/edit'
  #
  # get 'bill_check/update'
  #
  # get 'bill_check/create'

  # get 'users/index'
  #
  # get 'users/viewmenu'
  #
  # get 'users/order_history'
  #
  # get 'users/logout_user'

  # get 'table_management2s/create'

  # get 'table_managements2/index'
  #
  # get 'table_managements2/create'
  #
  # get 'table_managements2/show'
  #
  # get 'table_managements2/new'

  # get 'table_managements/create'
  #
  # get 'table_managements/new'
  #
  # get 'table_managements/index'
  #
  # get 'table_managements/show'
  #
  # get 'table_managements/edit'
  #
  # get 'table_managements/delete'
  #
  # get 'menu_managements/index'
  #
  # get 'menu_managements/new'
  #
  # get 'menu_managements/show'
  #
  # get 'menu_managements/create'
  #
  # get 'menu_managements/edit'
  #
  # get 'menu_managements/delete'
  #
  # get 'select_branches/index'
  #
  # get 'select_branches/new'
  #
  # get 'select_branches/create'
  #
  # get 'select_branches/show'
  #
  # get 'makebrs/index'
  #
  # get 'makebrs/new'
  #
  # get 'makebrs/show'
  #
  # get 'makebs/index'
  #
  # get 'makebs/new'
  #
  # get 'makebranches/index'
  #
  # get 'makebranches/new'
  #
  # get 'makebranch/index'
  #
  # get 'makebranch/create'
  #
  # get 'makebranch/show'
  #
  # get 'makebranch/new'
  #
  # get 'make_branches/index'
  #
  # get 'make_branches/new'
  #
  # get 'make_branches/show'
  #
  # get 'make_branches/create'
  #
  # get 'make_branch/index'
  #
  # get 'make_branch/create'
  #
  # get 'make_branch/show'
  #
  # get 'make_branch/new'
  #
  # get 'session2/create'
  root 'homes#index'

  get 'users/order_history'
  get 'users/menual_user'


  resources :homes
  resources :sessions
  resources :select_branches
  resources :operators
  resources :makebrs
  resources :users
  resources :menu_managements
  get 'menu_managements/new/:br_id' => 'menu_managements#new'
  # get 'menu_managements/index/:br_id' => 'menu_managements#index'
  resources :table_management2s
  resources :table_managements
  resources :bill_checks
  get 'table_managements/new/:br_id' => 'table_managements#new'
  get 'table_managements/index/:br_id' => 'table_managements#index'
  get 'menu_managements/create/:br_id' => 'menu_managements#create'
  delete 'menu_managements/destroy/:br_id' => 'menu_managements#destroy'
  get 'menu_managements/delete/:br_id' => 'menu_managements#delete'
  get 'menu_managements/update/:br_id' => 'menu_managements#update'
  get 'menu_managements/edit/:br_id' => 'menu_managements#edit'
  get 'bill_check/show/:br_id' => 'bill_check#show'
  get 'bill_check/index/:br_id' => 'bill_check#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord

  has_many :seat_strutures
  belongs_to :operator

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :orders
  belongs_to :branch
  mount_uploader :image, AvatarUploader
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :branches
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  before_save {self.email=email.downcase}
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true,
            format:{with: VALID_EMAIL_REGEX},
           uniqueness: {case_sensitive: false}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :menu
  belongs_to :seat_onuse
end

app/models/seat_onuse.rb
class SeatOnuse < ApplicationRecord
  has_many :orders
  belongs_to :seat_struture, optional: true
end

app/models/seat_struture.rb
class SeatStruture < ApplicationRecord
  belongs_to :branch
  has_many :seat_onuses
end

app/models/user.rb
class User < ApplicationRecord

  has_many :branches

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new

  end

  #회원가입 하면 여기로 데이터 옴
  def create

  end

  def show

  end

  def index

  end

end

app/controllers/makebrs_controller.rb
class MakebrsController < ApplicationController
  def index
    @op = Operator.where(operator_id: session[:operator_id])
  end

  def new
    @token = form_authenticity_token
  end

  def show
  end

  def create
    op_id = params[:op_id].to_s
    @br = Branch.create(
        universe: params[:branch_school],
        major: params[:branch_major],
        operator_id: op_id
    )

    redirect_to select_branches_path  # 브렌치 선택으로 이동.
  end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  def create
    @op=Operator.create(
                  email: params[:email],
                  password: params[:password],
                  phone: params[:operator_phone],
                  name: params[:operator_name]
    )

    redirect_to '/homes#index'
  end

  def index

  end
  def show

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, :only => :create
  def create
      #로그인 확인
      confirm_id=params[:op_id]

      if confirm_id.include?"@"
        #운영자 아이디면
        operator=Operator.find_by(email: params[:op_id])
        if operator && operator.authenticate(params[:password])
          log_in_operator(operator)
          redirect_to select_branches_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end

      else
        #사용자 아이디면
        table=SeatOnuse.find(params[:op_id])
        if table && table.hash_code==params[:password]
          log_in_user(table)
          redirect_to users_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end
      end

  end

  def destroy
    log_out
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def viewmenu
  end

  def index
  end

  def order_history
  end

  def logout_user
  end

  def menual_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_checks_helper.rb
module BillChecksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/makebrs_helper.rb
module MakebrsHelper
end

app/helpers/menu_managements_helper.rb
module MenuManagementsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/select_branches_helper.rb
module SelectBranchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in_operator(operator)
    session[:operator_id]=operator.id
  end

  def log_in_user(table)
    session[:table_id]=table.id
  end

  def confirm_log_in?(confirm_id)
    #마지막줄 리턴
    email_format==/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  end

  def current_operator
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

   @current_operator ||= Operator.find_by(id: session[:operator_id])
  end

  def current_user
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

    @current_user||= SeatOnuse.find(session[:table_id])
  end

  def operator_signed_in?
    !current_operator.nil?
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="login_wrap">
  <form action="<%= sessions_path %>" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    
  <header class="login_logo"></header>
  <section class="login_display">
    <input class="ID_login" type="text" placeholder="ID" name="op_id" >
    <p>
      <input class="pw_login" type="password" placeholder="Password" name="password" >
    <p>
      <input class="submit_login" type="submit"  value="로그인">
    <p>
      <%= link_to '운영자 회원가입', new_operator_path %>
  </section> <!-- login_display end -->
  </form>
</div> <!-- login_wrap end -->

app/views/homes/new.html.erb
<h>회원가입</h>

<form action="<%= operators_path %>" method="post" id="signin_form" data-ajax="false">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="register_wrap">
    <header class="register_logo"></header>
    <section class="register_display">

      <table>
        <tr>
          <td>아이디 </td>
          <td><input type="text" name="operator_id"></td>
        </tr>
        <tr>
          <td>비밀번호 </td>
          <td><input type="password" id="Pw" name="password" required></td>
        </tr>
        <tr>
          <td>비밀번호 확인 </td>
          <td>
            <input type="password" id="PwCheck" name="password_confirmation" required>
             <p id="pwsame" class="pwsame" style="color:red;"></p>
            <br><br>
          </td>
        </tr>

        <tr>
          <td>이름</td>
          <td><input type="text" name="operator_name"></td>
        </tr>
        <tr>
          <td>전화번호 </td>
          <td><input type="number" name="operator_phone"></td>
        </tr>
      </table>

      <input class="next_register" type="submit" value="다음">
    </section> <!-- login_display end -->
  </div> <!-- login_wrap end -->


</form>

app/views/homes/show.html.erb
<form action="/operators/second_create" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="register_wrap">
    <header class="register_logo"></header>
    <section class="register_display">

      <table>
        <tr>
          <td>학교 </td>
          <td><input type="text" name="uni"></td>
        </tr>
        <tr>
          <td>학과 </td>
          <td><input type="text"></td>
        </tr>

      </table>

      <input class="submit_register" type="submit" value="회원가입">
    </section> <!-- login_display end -->
  </div> <!-- login_wrap end -->
</form>

app/views/homes/user_main.html.erb
<section class="main-login">

  <ul class="main-login-here">

    <li>로그인</li>
    <li>회원가입</li>
  </ul>

</section>

<header class="main-logo">
  <div class="main-logo-left"></div>
  <div class="main-logo-mid"></div>
  <div class="main-logo-right"></div>

</header>



<nav class="main-menu">
  <ul class = "main-menu-item">
    <li></li>
    <li></li>
    <li>주문하기</li>
    <li>주문내역</li>
    <li>사용법 영상</li>
  </ul>
</nav>


<section class="video">

  <iframe width="668" height="376" src="https://www.youtube.com/embed/3MRvKJZEd6w" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

</section>

app/views/makebrs/create.html.erb
<h1>Makebrs#create</h1>
<p>Find me in app/views/makebrs/create.html.erb</p>

app/views/makebrs/index.html.erb
<h1>Makebrs#index</h1>
<p>Find me in app/views/makebrs/index.html.erb</p>

app/views/makebrs/new.html.erb
<div class="total">


  <header class="main_logo"></header>
  <section class="makebrs_display">
    <!--      <p><%=session[:operator_id]%></p> -->

    <form action="<%= makebrs_path %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= @token %>">
      <input type="hidden" name="op_id" value="<%= session[:operator_id] %>">
      <input type="text" name="branch_school" placeholder="학교">
      <br>
      <input type="text" name="branch_major" placeholder="학과">
      <br>
      <input type="submit" value="지점만들기">
    </form>
  </section> <!-- login_display end -->

</div> <!-- login_wrap end -->

app/views/makebrs/show.html.erb
<h1>Makebrs#show</h1>
<p>Find me in app/views/makebrs/show.html.erb</p>