config/routes.rb
Rails.application.routes.draw do

  # get 'bill_checks/index'
  #
  # get 'bill_checks/new'
  #
  # get 'bill_checks/create'
  #
  # get 'bill_checks/show'
  #
  # get 'bill_checks/update'
  #
  # get 'bill_checks/edit'
  #
  # get 'bill_check/index'
  #
  # get 'bill_check/new'
  #
  # get 'bill_check/show'
  #
  # get 'bill_check/edit'
  #
  # get 'bill_check/update'
  #
  # get 'bill_check/create'

  # get 'users/index'
  #
  # get 'users/viewmenu'
  #
  # get 'users/order_history'
  #
  # get 'users/logout_user'

  # get 'table_management2s/create'

  # get 'table_managements2/index'
  #
  # get 'table_managements2/create'
  #
  # get 'table_managements2/show'
  #
  # get 'table_managements2/new'

  # get 'table_managements/create'
  #
  # get 'table_managements/new'
  #
  # get 'table_managements/index'
  #
  # get 'table_managements/show'
  #
  # get 'table_managements/edit'
  #
  # get 'table_managements/delete'
  #
  # get 'menu_managements/index'
  #
  # get 'menu_managements/new'
  #
  # get 'menu_managements/show'
  #
  # get 'menu_managements/create'
  #
  # get 'menu_managements/edit'
  #
  # get 'menu_managements/delete'
  #
  # get 'select_branches/index'
  #
  # get 'select_branches/new'
  #
  # get 'select_branches/create'
  #
  # get 'select_branches/show'
  #
  # get 'makebrs/index'
  #
  # get 'makebrs/new'
  #
  # get 'makebrs/show'
  #
  # get 'makebs/index'
  #
  # get 'makebs/new'
  #
  # get 'makebranches/index'
  #
  # get 'makebranches/new'
  #
  # get 'makebranch/index'
  #
  # get 'makebranch/create'
  #
  # get 'makebranch/show'
  #
  # get 'makebranch/new'
  #
  # get 'make_branches/index'
  #
  # get 'make_branches/new'
  #
  # get 'make_branches/show'
  #
  # get 'make_branches/create'
  #
  # get 'make_branch/index'
  #
  # get 'make_branch/create'
  #
  # get 'make_branch/show'
  #
  # get 'make_branch/new'
  #
  # get 'session2/create'
  root 'homes#index'

  get 'users/order_history'
  get 'users/menual_user'


  resources :homes
  resources :sessions
  resources :select_branches
  resources :operators
  resources :makebrs
  resources :users
  resources :menu_managements
  get 'menu_managements/new/:br_id' => 'menu_managements#new'
  # get 'menu_managements/index/:br_id' => 'menu_managements#index'
  resources :table_management2s
  resources :table_managements
  resources :bill_checks
  get 'table_managements/new/:br_id' => 'table_managements#new'
  get 'table_managements/index/:br_id' => 'table_managements#index'
  get 'menu_managements/create/:br_id' => 'menu_managements#create'
  delete 'menu_managements/destroy/:br_id' => 'menu_managements#destroy'
  get 'menu_managements/delete/:br_id' => 'menu_managements#delete'
  get 'menu_managements/update/:br_id' => 'menu_managements#update'
  get 'menu_managements/edit/:br_id' => 'menu_managements#edit'
  get 'bill_check/show/:br_id' => 'bill_check#show'
  get 'bill_check/index/:br_id' => 'bill_check#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord

  has_many :seat_strutures
  belongs_to :operator

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :orders
  belongs_to :branch
  mount_uploader :image, AvatarUploader
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :branches
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  before_save {self.email=email.downcase}
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true,
            format:{with: VALID_EMAIL_REGEX},
           uniqueness: {case_sensitive: false}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :menu
  belongs_to :seat_onuse
end

app/models/seat_onuse.rb
class SeatOnuse < ApplicationRecord
  has_many :orders
  belongs_to :seat_struture, optional: true
end

app/models/seat_struture.rb
class SeatStruture < ApplicationRecord
  belongs_to :branch
  has_many :seat_onuses
end

app/models/user.rb
class User < ApplicationRecord

  has_many :branches

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new

  end

  #회원가입 하면 여기로 데이터 옴
  def create

  end

  def show

  end

  def index

  end

end

app/controllers/makebrs_controller.rb
class MakebrsController < ApplicationController
  def index
    @op = Operator.where(operator_id: session[:operator_id])
  end

  def new
    @token = form_authenticity_token
  end

  def show
  end

  def create
    op_id = params[:op_id].to_s
    @br = Branch.create(
        universe: params[:branch_school],
        major: params[:branch_major],
        operator_id: op_id
    )

    redirect_to select_branches_path  # 브렌치 선택으로 이동.
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, :only => :create
  def create
      #로그인 확인
      confirm_id=params[:op_id]

      if confirm_id.include?"@"
        #운영자 아이디면
        operator=Operator.find_by(email: params[:op_id])
        if operator && operator.authenticate(params[:password])
          log_in_operator(operator)
          redirect_to select_branches_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end

      else
        #사용자 아이디면
        table=SeatOnuse.find(params[:op_id])
        if table && table.hash_code==params[:password]
          log_in_user(table)
          redirect_to users_path, method: :get
        else
          flash[:alert]="아이디 혹은 비밀번호가 일치하지 않습니다."
          redirect_to homes_path, method: :get
        end
      end

  end

  def destroy
    log_out
    redirect_to :root
  end

end

app/controllers/table_managements_controller.rb
class TableManagementsController < ApplicationController
  def create

    @token = form_authenticity_token
    i = 0

    while i < params[:table_number].to_i

      @seatstruct = SeatStruture.create(
          status: "off",
          branch_id: params[:br_id]
      )
      i+=1

    end

    redirect_to new_table_management_path + '/' + params[:br_id]
  end

  def new
    @token = form_authenticity_token
    @t_id = SeatStruture.where(branch_id: params[:br_id])


  end

  def index

    @t_id = SeatStruture.where(branch_id: params[:br_id])
    @token = form_authenticity_token


  end

  def show
  end

  def edit
  end

  def delete
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def viewmenu
  end

  def index
  end

  def order_history
  end

  def logout_user
  end

  def menual_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bill_checks_helper.rb
module BillChecksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/makebrs_helper.rb
module MakebrsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/select_branches_helper.rb
module SelectBranchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in_operator(operator)
    session[:operator_id]=operator.id
  end

  def log_in_user(table)
    session[:table_id]=table.id
  end

  def confirm_log_in?(confirm_id)
    #마지막줄 리턴
    email_format==/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  end

  def current_operator
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

   @current_operator ||= Operator.find_by(id: session[:operator_id])
  end

  def current_user
    #계속해서 디비에 접근하는 부하를 해결하기 위해
    # 한번 접근하고 변수에 저장해놈

    @current_user||= SeatOnuse.find(session[:table_id])
  end

  def operator_signed_in?
    !current_operator.nil?
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
  end
end

app/helpers/table_managements_helper.rb
module TableManagementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/table_managements/create.html.erb
<% @tableStructure.each do |x| %>
  <div>
    <p><%=x.id%></p>
    <p><%=x.name%></p>

    <form action="<%=table_onuses_path%>" method="post">
      <input type="hidden" name = "authenticity_token" value="<%=@token%>">
      <input type="hidden" name = "struct_id" value = "<%=x.id%>">
      <input type="submit" value="생성">
    </form>

  </div>
<% end %>

app/views/table_managements/index.html.erb
<h1>테이블 메인</h1>

<br><br>
<%= link_to '테이블 만들기', '/table_managements/new/'+params[:br_id] %>
<br><br>
<%= link_to '테이블 수정하기', '#' %>
<br><br>
<%= link_to '테이블 삭제하기', '#' %>
<br><br>
<br>

<div class="table-struct"></div>
<% @t_id.each do |x| %>
  <div class="table-struct-part">
    <p><%=x.id%></p>
    <p><%=x.status%></p>

    <form action="<%= table_management2s_path %>" method="post">
      <input type="hidden" name = "authenticity_token" value="<%=@token%>">
      <input type="hidden" name = "table_id" value = "<%=x.id%>">
      <input type="submit" value="클릭">
    </form>

  </div>
<% end %>

app/views/table_managements/new.html.erb
<div class="operator_wrap">
  <% if operator_signed_in? %>
    로그인한 유저:
    <%= current_operator.email %>
  <% end %>
  <p><%= link_to '로그아웃', session_path(current_operator.email), method: 'delete' %></p>
  <div class="operator_logo"></div>
  <nav class="operator_bar_nav">
    <ul class="operator_bar_list">
      <hr>
      <%= link_to '주문 현황', '/bill_checks/index/' + params[:br_id] %>
      <a href="#">테이블 생성</a>
      <%= link_to '메뉴', '/menu_managements/new/'+params[:br_id] %>
      <a href="#">사용법</a>
      <hr>
    </ul>
    <ul class="menu_bar">
      <div class="test">
        <%= link_to '메뉴 생성', '/menu_managements/new/'+params[:br_id] %>
        <a href="#">메뉴 수정</a>
        <a href="#">메뉴 삭제</a>
      </div>
    </ul>

  </nav>

</div>

<wrap class="back">
  <div class="table_mg_section">
    <form action="<%= table_managements_path %>" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input type="text" name="table_number" placeholder="테이블 수">
      <input type="hidden" name="br_id" value="<%=params[:br_id]%>">
      <br>
      <input type="submit" value="만들기">
    </form>

  </div>

</wrap>


<br><br><br><br><br><br>
<% @t_id.each do |x| %>
  <div>
    <p><%=x.id%></p>
    <p><%=x.status%></p>

    <form action="<%= table_management2s_path%>" method="post">
      <input type="hidden" name = "authenticity_token" value="<%=@token%>">
      <input type="hidden" name = "table_id" value = "<%=x.id%>">
      <input type="hidden" name = "br_id" value="<%=x.branch_id %>">
      <input type="submit" value="클릭">
    </form>

    <%= link_to table_management_path(x.id), method: 'delete' do %>
      <input type="hidden" name="authenticity_token" value="<%= @token %>">
      <input type="hidden" name="br_id" value="<%= x.branch_id %>">
      <button>삭제하기</button><br>
    <% end %>
    <br><br>

  </div>
<% end %>

app/views/table_managements/show.html.erb
<h1>this is show of table_managements</h1>